services:
  redis:
    image: redis:7-alpine
    container_name: notepia-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  notepia-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: notepia/notepia:local
    container_name: notepia-web
    command: ["./web"]
    ports:
      - "8080:8080"
    volumes:
      - "./bin:/usr/local/app/bin"
    environment:
      - PORT=8080
      - APP_DISABLE_SIGNUP=${APP_DISABLE_SIGNUP}
      - APP_SECRET=${APP_SECRET}
      - REDIS_ADDR=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  notepia-worker:
    image: notepia/notepia:local
    container_name: notepia-worker
    command: ["./worker"]
    volumes:
      - "./bin:/usr/local/app/bin"
    environment:
      - APP_SECRET=${APP_SECRET}
      - REDIS_ADDR=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
    driver: local